info:
  scm-url: "@scm.url@"
  build-url: "https://travis-ci.org/codecentric/spring-boot-admin"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://localhost:8082
                metadata:
                  management.context-path: /actuator
